[package]
name = "dloc-cli"
version = "0.2.4"
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dloc-core = { path = "../dloc-core" }
