name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Linux dependencies
        run: sudo apt update
        if: contains(matrix.os, 'ubuntu')

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Build
        run: cargo build --verbose --all-features

      - name: Clippy
        run: cargo clippy --verbose  --all-features -- -D warnings
        
      - name: Audit
        run: cargo audit --deny warnings